// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutinR.SQLite;

#nullable disable

namespace RoutinR.SQLite.Migrations
{
    [DbContext(typeof(RoutinRContext))]
    [Migration("20230401194452_Adding_Jobs_TimeSheetEntries_and_ApiProfiles")]
    partial class Adding_Jobs_TimeSheetEntries_and_ApiProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("RoutinR.SQLite.Entities.ApiExportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndTimeToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTimeToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiExportProfiles");
                });

            modelBuilder.Entity("RoutinR.SQLite.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("RoutinR.SQLite.Entities.JobTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiExportProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiExportProfileId");

                    b.HasIndex("KeyId");

                    b.ToTable("JobTemplates");
                });

            modelBuilder.Entity("RoutinR.SQLite.Entities.TimeSheetEntry", b =>
                {
                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StartTime", "EndTime");

                    b.HasIndex("JobId");

                    b.ToTable("TimeSheetEntries");
                });

            modelBuilder.Entity("RoutinR.SQLite.Entities.JobTemplate", b =>
                {
                    b.HasOne("RoutinR.SQLite.Entities.ApiExportProfile", "ApiExportProfile")
                        .WithMany()
                        .HasForeignKey("ApiExportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutinR.SQLite.Entities.Job", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiExportProfile");

                    b.Navigation("Key");
                });

            modelBuilder.Entity("RoutinR.SQLite.Entities.TimeSheetEntry", b =>
                {
                    b.HasOne("RoutinR.SQLite.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
