name: build_validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 7.0.103
    #ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
jobs:
  Test_On_Windows_2022:
    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'
                
      - name: Install dependencies
        run: dotnet restore src\RoutinR.sln
      - name: Build
        run: dotnet build src\RoutinR.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test src\RoutinR.sln --no-restore --verbosity normal
